export const ASSOCIATION_COLORS: Record<string, string> = {
  "Emmaüs Solidarité": "#8B2019",
  "La Chorba": "#1a5276",
  Aurore: "#1d6a3a",
  "Samu Social de Paris": "#5d4037",
  "Les Enfants du Canal": "#6a3d9a",
  // Diocèse de Paris
  "Secours Catholique – Caritas Paris": "#b5600a",
  "Aux Captifs la Libération": "#7b1fa2",
  "Les Petits Frères des Pauvres": "#006064",
  "La Mie de Pain": "#c62828",
  Lazare: "#283593",
  "Fraternité Notre-Dame": "#2e7d32",
  // Paroisses / Diocèse
  "CSVP – Diocèse de Paris": "#3e2723",
  "La Rue Tourne": "#004d40",
  "Li'llah": "#311b92",
  "Communauté Sant'Egidio": "#880e4f",
  "La Bagagerie d'Antigel": "#37474f",
  // Grandes organisations
  "Croix-Rouge Française": "#c0392b",
  "Ordre de Malte France": "#1565c0",
  "Les Restos du Cœur": "#ef6c00",
  "Secours Populaire": "#b71c1c",
  "Armée du Salut": "#f9a825",
  "Médecins du Monde": "#01579b",
  "Utopia 56": "#00838f",
  "Dans Ma Rue": "#e65100",
  "Robins des Rues": "#4e342e",
  // Communautés chrétiennes
  "Communauté du Chemin Neuf": "#7b3f00",
  "Compagnie des Laveurs de Pieds": "#5c4033",
  "Magis Solidarité": "#002366",
  "Macadam Café": "#8b0000",
  "Entraides Citoyennes": "#2e8b57",
  "MESL": "#0e4d4d",
  // Associations professionnelles
  "Oppélia": "#1b5e20",
  // Associations étudiantes
  "La Balade des Lucioles": "#f57f17",
  "UCPH": "#6a1b9a",
  "Paris Solidaires": "#ad1457",
  // Associations musulmanes
  "Une Chorba Pour Tous": "#00695c",
  "Au Cœur de la Précarité": "#bf360c",
  "Association Miséricorde": "#0d47a1",
  "Un Pas Vers Demain": "#558b2f",
  // Paroisses – Diocèse de Paris
  "Club Saint Vincent des Isles": "#8a2828",
  "Conférence Saint-Vincent de Paul": "#8a2e28",
  "E quipes Saint Vincent - 67, rue de Sèvres Paris": "#8a3428",
  "Espace Saint-Jean-Baptiste": "#8a3b28",
  "Paris Centre - CERISE": "#8a4128",
  "Paroisse Bon Pasteur": "#8a4728",
  "Paroisse Immaculée Conception": "#8a4e28",
  "Paroisse Notre-Dame de Bercy": "#8a5428",
  "Paroisse Notre-Dame de Clignancourt": "#8a5a28",
  "Paroisse Notre-Dame de Compassion": "#8a6128",
  "Paroisse Notre-Dame de Grâce de Passy": "#8a6728",
  "Paroisse Notre-Dame de La Salette": "#8a6d28",
  "Paroisse Notre-Dame de Lorette": "#8a7428",
  "Paroisse Notre-Dame de Nazareth": "#8a7a28",
  "Paroisse Notre-Dame de la Croix": "#8a8028",
  "Paroisse Notre-Dame de la Gare": "#8a8728",
  "Paroisse Notre-Dame de l’Arche d’Alliance": "#878a28",
  "Paroisse Notre-Dame de l’Assomption de Passy": "#808a28",
  "Paroisse Notre-Dame de l’Assomption des Buttes Chaumont": "#7a8a28",
  "Paroisse Notre-Dame des Blancs-Manteaux": "#748a28",
  "Paroisse Notre-Dame des Champs": "#6d8a28",
  "Paroisse Notre-Dame du Bon Conseil": "#678a28",
  "Paroisse Notre-Dame du Perpétuel Secours": "#618a28",
  "Paroisse Notre-Dame du Rosaire": "#5a8a28",
  "Paroisse Notre-Dame d’Auteuil": "#548a28",
  "Paroisse Notre-Dame d’Espérance": "#4e8a28",
  "Paroisse Saint-Albert-le-Grand": "#478a28",
  "Paroisse Saint-Ambroise": "#418a28",
  "Paroisse Saint-André de l’Europe": "#3b8a28",
  "Paroisse Saint-Antoine de Padoue": "#348a28",
  "Paroisse Saint-Antoine des Quinze-Vingts": "#2e8a28",
  "Paroisse Saint-Augustin": "#288a28",
  "Paroisse Saint-Christophe de Javel": "#288a2e",
  "Paroisse Saint-Denys de la Chapelle": "#288a34",
  "Paroisse Saint-Dominique": "#288a3b",
  "Paroisse Saint-Esprit": "#288a41",
  "Paroisse Saint-Eustache": "#288a47",
  "Paroisse Saint-Ferdinand des Ternes - Sainte-Thérèse de l’Enfant-Jésus": "#288a4e",
  "Paroisse Saint-François de Molitor": "#288a54",
  "Paroisse Saint-François de Sales": "#288a5a",
  "Paroisse Saint-François-Xavier": "#288a61",
  "Paroisse Saint-Gabriel": "#288a67",
  "Paroisse Saint-Georges de la Villette": "#288a6d",
  "Paroisse Saint-Germain de Charonne": "#288a74",
  "Paroisse Saint-Germain des Prés": "#288a7a",
  "Paroisse Saint-Hippolyte": "#288a80",
  "Paroisse Saint-Honoré d’Eylau": "#288a87",
  "Paroisse Saint-Jacques - Saint-Christophe de la Villette": "#28878a",
  "Paroisse Saint-Jacques du Haut-Pas": "#28808a",
  "Paroisse Saint-Jean Bosco": "#287a8a",
  "Paroisse Saint-Jean de Montmartre": "#28748a",
  "Paroisse Saint-Jean-Baptiste de Belleville": "#286d8a",
  "Paroisse Saint-Jean-Baptiste de Grenelle": "#28678a",
  "Paroisse Saint-Jean-Baptiste de La Salle": "#28618a",
  "Paroisse Saint-Joseph des Nations": "#285a8a",
  "Paroisse Saint-Joseph des Épinettes": "#28548a",
  "Paroisse Saint-Joseph-Artisan": "#284e8a",
  "Paroisse Saint-Lambert de Vaugirard": "#28478a",
  "Paroisse Saint-Laurent": "#28418a",
  "Paroisse Saint-Leu - Saint-Gilles": "#283b8a",
  "Paroisse Saint-Louis d’Antin": "#28348a",
  "Paroisse Saint-Luc": "#282e8a",
  "Paroisse Saint-Léon": "#28288a",
  "Paroisse Saint-Marcel": "#2e288a",
  "Paroisse Saint-Michel": "#34288a",
  "Paroisse Saint-Médard": "#3b288a",
  "Paroisse Saint-Nicolas des Champs": "#41288a",
  "Paroisse Saint-Paul - Saint-Louis": "#47288a",
  "Paroisse Saint-Pierre de Chaillot": "#4e288a",
  "Paroisse Saint-Pierre de Montrouge": "#54288a",
  "Paroisse Saint-Pierre du Gros Caillou": "#5a288a",
  "Paroisse Saint-Roch": "#61288a",
  "Paroisse Saint-Sulpice": "#67288a",
  "Paroisse Saint-Séverin - Saint-Nicolas": "#6d288a",
  "Paroisse Saint-Thomas d’Aquin": "#74288a",
  "Paroisse Saint-Vincent de Paul": "#7a288a",
  "Paroisse Saint-Éloi": "#80288a",
  "Paroisse Saint-Étienne du Mont": "#87288a",
  "Paroisse Sainte-Anne de la Butte-aux-Cailles": "#8a2887",
  "Paroisse Sainte-Claire": "#8a2880",
  "Paroisse Sainte-Clotilde": "#8a287a",
  "Paroisse Sainte-Geneviève des Grandes Carrières": "#8a2874",
  "Paroisse Sainte-Hélène": "#8a286d",
  "Paroisse Sainte-Jeanne de Chantal": "#8a2867",
  "Paroisse Sainte-Madeleine": "#8a2861",
  "Paroisse Sainte-Marguerite": "#8a285a",
  "Paroisse Sainte-Marie des Batignolles": "#8a2854",
  "Paroisse Sainte-Odile": "#8a284e",
  "Paroisse Sainte-Rosalie": "#8a2847",
  "Paroisse Sainte-Trinité": "#8a2841",
  "Paroisse Sainte-Élisabeth de Hongrie": "#8a283b",
  "Petits-déjeuners": "#8a2834",
  "S’adresse plus particulièrement aux personnes seules ou âgées du quartier, pour leur permettre de se rencontrer, bavarder, jouer, le vendredi tous les 15 jours de 14h30 à 17h, une sortie annuelle et un repas festif à Noël.": "#8a282e",

};

export const ALL_ASSOCIATIONS = Object.keys(ASSOCIATION_COLORS);
